name: hiddify
description: Windows VPN Proxy Client (Hiddify Fork).
publish_to: "none"
version: 2.5.7+20507

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  humanizer: ^3.0.1

  # State management & functional programming
  slang: ^4.12.0
  slang_flutter: ^4.12.0
  fpdart: ^1.1.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  hooks_riverpod: ^3.1.0
  riverpod: ^3.1.0
  flutter_hooks: ^0.21.3+1
  riverpod_annotation: ^4.0.0
  rxdart: ^0.28.0

  # Database & storage
  drift: ^2.30.1
  sqlite3_flutter_libs: ^0.5.24
  shared_preferences: ^2.2.2

  # Network
  dio: ^5.4.1
  dio_smart_retry: ^7.0.1
  http: ^1.2.0

  # Windows specific
  ffi: ^2.1.5
  path_provider: ^2.1.1
  window_manager: ^0.5.1
  tray_manager: ^0.5.2
  package_info_plus: ^9.0.0
  url_launcher: ^6.2.5
  launch_at_startup: ^0.5.1
  win32: ^5.2.0

  # Utilities
  path: ^1.8.3
  loggy: ^2.0.3
  flutter_loggy: ^2.0.2
  flutter_loggy_dio: ^3.0.1
  meta: ^1.10.0
  dartx: ^1.2.0
  uuid: ^4.3.3
  tint: ^2.0.1
  neat_periodic_task: ^2.0.1
  watcher: ^1.2.1
  version: ^3.0.2
  timezone_to_country: ^3.1.0
  json_path: ^0.9.0

  # UI
  go_router: ^17.0.0
  flutter_animate: ^4.5.0
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  percent_indicator: ^4.2.3
  sliver_tools: ^0.2.12
  toastification: ^3.0.3
  qr_flutter: ^4.1.0
  wolt_modal_sheet: ^0.11.0
  dart_mappable: ^4.2.1
  fluentui_system_icons: ^1.1.229
  dynamic_color: ^1.7.0
  flutter_typeahead: ^5.0.1
  circle_flags: ^5.0.1
dev_dependencies:
  lint: ^2.3.0
  build_runner: ^2.10.5
  json_serializable: ^6.7.1
  freezed: ^3.2.3
  riverpod_generator: ^4.0.0+1
  drift_dev: ^2.30.1
  ffigen: ^20.1.1
  slang_build_runner: ^4.12.0
  flutter_gen_runner: ^5.4.0
  go_router_builder: ^4.1.3
  dart_mappable_builder: ^4.2.1

dependency_overrides:
  # drift & package_info_plus are not compatible
  web: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.svg
    - assets/images/tray_icon.ico
    - assets/images/tray_icon.png
    - assets/images/tray_icon_dark.ico
    - assets/images/tray_icon_dark.png
    - assets/images/tray_icon_connected.ico
    - assets/images/tray_icon_connected.png
    - assets/images/tray_icon_disconnected.ico
    - assets/images/tray_icon_disconnected.png
    - assets/images/connect_norouz.PNG
    - assets/images/disconnect_norouz.PNG

  fonts:
    - family: Shabnam
      fonts:
        - asset: assets/fonts/Shabnam.ttf
    - family: Emoji
      fonts:
        - asset: assets/fonts/Emoji.ttf

flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true

ffigen:
  name: "SingboxNativeLibrary"
  description: "Bindings to Singbox"
  output: "lib/gen/singbox_generated_bindings.dart"
  headers:
    entry-points:
      - "libcore/bin/libcore.h"

